name: petcoin
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

# dependencies:
#   flutter:
#     sdk: flutter

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  flutter_local_notifications: ^12.0.4 
  


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2


  google_nav_bar: ^5.0.6
  fl_chart: ^0.68.0
  toggle_switch: ^2.3.0
  firebase_core: ^2.31.1
  firebase_auth: ^4.19.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/images/bell_with_notification.png
  uses-material-design: true
