// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHK0X3BicVYVrh1eUuGWYiM73Ph1UQV6U',
    appId: '1:591556506636:web:852591c92b5f7a1091ea29',
    messagingSenderId: '591556506636',
    projectId: 'petcoin-oop-project',
    authDomain: 'petcoin-oop-project.firebaseapp.com',
    storageBucket: 'petcoin-oop-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSe5bEI6OsOxH6STIzl3KAOuCJJMzWu7A',
    appId: '1:591556506636:android:86e65a93902c543591ea29',
    messagingSenderId: '591556506636',
    projectId: 'petcoin-oop-project',
    storageBucket: 'petcoin-oop-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHmRvlTNbxwhWZY1P9BMZ0sBSNifdf0SM',
    appId: '1:591556506636:ios:7d605a643cd3c0c091ea29',
    messagingSenderId: '591556506636',
    projectId: 'petcoin-oop-project',
    storageBucket: 'petcoin-oop-project.appspot.com',
    iosBundleId: 'com.example.petcoin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHmRvlTNbxwhWZY1P9BMZ0sBSNifdf0SM',
    appId: '1:591556506636:ios:7d605a643cd3c0c091ea29',
    messagingSenderId: '591556506636',
    projectId: 'petcoin-oop-project',
    storageBucket: 'petcoin-oop-project.appspot.com',
    iosBundleId: 'com.example.petcoin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHK0X3BicVYVrh1eUuGWYiM73Ph1UQV6U',
    appId: '1:591556506636:web:2f7a88d7995185ad91ea29',
    messagingSenderId: '591556506636',
    projectId: 'petcoin-oop-project',
    authDomain: 'petcoin-oop-project.firebaseapp.com',
    storageBucket: 'petcoin-oop-project.appspot.com',
  );
}
